functionsDirectory = "/opt/build/repo/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/opt/build/repo/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "vite build"
functions = "/opt/build/repo/netlify/functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[database]

  [database.migrations]
  path = "/opt/build/repo/netlify/database/migrations"

[functions]

  [functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]